# Generated by Django 4.2.7 on 2023-11-14 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_admin_user_document_number_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
    ]
